### ISSUE TITLE
[POLL] Scheduling bi-weekly deep-dive (Wednesday, March 11th 2020)

### ISSUE THREAD

**Issue by darcyclarke** [npm/rfcs#105]
After getting some feedback in our most recent [**Open RFC call**](https://www.youtube.com/watch?v=wR0XZs6OFaA) we've decided to schedule a bi-weekly "deep-dive" call that will take on one RFC, PR, issue or overall topic of discussion to allow for more in-depth conversations to happen. 

The deep-dive topic will be chosen at the preceding Open RFC call for visibility (notably, the first call will be focused around ["Workspaces"](https://github.com/npm/rfcs/pull/103)).

With that in mind, we'd like to poll the community to help choose the timing of this call. Unfortunately, our team has limited availability beyond the existing **Wednesdsay 2pm ET** timeslot. 

Here are the current options:

[![](https://api.gh-polls.com/poll/01E2EK1QWSR9ACFTWWJ41G0214/Wednesday%201pm%20ET)](https://api.gh-polls.com/poll/01E2EK1QWSR9ACFTWWJ41G0214/Wednesday%201pm%20ET/vote)
[![](https://api.gh-polls.com/poll/01E2EK1QWSR9ACFTWWJ41G0214/Wednesday%202pm%20ET)](https://api.gh-polls.com/poll/01E2EK1QWSR9ACFTWWJ41G0214/Wednesday%202pm%20ET/vote)
[![](https://api.gh-polls.com/poll/01E2EK1QWSR9ACFTWWJ41G0214/Wednesday%205pm%20ET)](https://api.gh-polls.com/poll/01E2EK1QWSR9ACFTWWJ41G0214/Wednesday%205pm%20ET/vote)

This poll will be closed this **Friday March 6th** & an [agenda issue/placeholder](https://github.com/npm/rfcs/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed+label%3Ameeting) will be created along w/ a corresponding event in our [public events calendar](https://calendar.google.com/calendar/embed?src=npmjs.com_oonluqt8oftrt0vmgrfbg6q6go%40group.calendar.google.com).

**Comment by ljharb** [comment]
Only Wednesdays?

**Comment by darcyclarke** [comment]
@ljharb yes, unfortunately. We've scheduled around the existing RFC day/time (ie. Wednesday @ 2pm ET) so most all other days/times have gotten booked up by competing org calls/activities.

**Comment by wesleytodd** [comment]
I voted for all three! I am sure that is not what was intended, but I can go to any of them, so it was either not vote or go all in.  One think to be clear, this will alternate with the existing call, right?

**Comment by darcyclarke** [comment]
@wesleytodd yes, this will be an alternating meeting to the existing Open RFC call; So you get a weekly dose of your friendly neighbourhood `npm` team 😉
