### ISSUE TITLE
Deep Dive Meeting - Wednesday, March 10, 2020, 2:00 PM EST

### ISSUE THREAD

**Issue by ruyadorno** [npm/rfcs#106]
## Why?
In our ongoing efforts to better listen to & collaborate with the community, we've started an Open RFC deep dive call that helps to move a specific conversation and/or initiative forward.

### Wednesday, March 10, 2020, 2:00 PM EST

**Cadence:**
This meeting is scheduled to take place **bi-weekly** alternating with our regular Open RFC calls. Previous meeting agendas and notes can be found [here](https://github.com/npm/rfcs/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed+label%3Ameeting)

**Add to your Calendar:**
You follow this & find other **npm** events by using our [public events calendar](https://calendar.google.com/calendar/embed?src=npmjs.com_oonluqt8oftrt0vmgrfbg6q6go%40group.calendar.google.com)

## What?

All discussions surrounding RFCs are covered by the [npm Code of Conduct](https://www.npmjs.com/policies/conduct). Please keep conversations constructive, civil & be mindful of when others are speaking. As is tradition, "raise your hand" when requesting to comment on a topic or request to comment asynchronously within the chat. The npm team may, at its own discretion, moderate, mute &/or remove a person from an Open RFC call for any reason.

### Agenda

1. **Housekeeping**
	1. Introduction(s)
	1. Code of Conduct Acknowledgement
	1. Outline Intentions & Desired Outcomes
	1. Announcements
1. **PR**: [#103 RFC: Add npm workspaces](https://github.com/npm/rfcs/pull/103)
	1. Scope (initial support and subsequent workspace-aware commands)
	1. Usecases (monorepos, multiple packages, etc)
	1. Install
	1. Subcommands
	1. Read configs

## How?

**Join Zoom Meeting**
https://npm.zoom.us/j/914742332

Meeting ID: 914 742 332

One tap mobile
+16465588656,,914742332# US (New York)
+16699006833,,914742332# US (San Jose)

Dial by your location
        +1 646 558 8656 US (New York)
        +1 669 900 6833 US (San Jose)
Meeting ID: 914 742 332
Find your local number: https://npm.zoom.us/u/abR8OFljr8

Meeting notes: https://hackmd.io/1Rfh3UJdQJiZkjidOD6l3g

**Watch the livestream**
https://youtu.be/CaXPbZesRiQ

**Comment by darcyclarke** [comment]
**Quick note/update:** The zoom call ID was changed just now. It should be up-to-date in the Public Events Calendar though.
