### ISSUE TITLE
💬 We're Testing out Discussions

### ISSUE THREAD

**Issue by darcyclarke** [npm/rfcs#136]
You'll see that we're moving some of our conversations around RFCs over to GitHub Discussions. I apologize beforehand as there will be some churn with respect to linking/discovery to start out with. We're hoping this will become the right home for conversations around `npm`, Questions & RRFCs.

**Comment by ljharb** [comment]
My feedback for github is that converting an issue to a discussion shouldn't generate a notification unless it generates a timeline item :-)

**Comment by darcyclarke** [comment]
@ljharb thats good feedback. Sorry for the spam <3

**Comment by wesleytodd** [comment]
One thing about discussions which I also have given as feedback, is that they do not have labels. This makes much of the categorization work difficult (a blocker for express to use them).  I know I have been slacking on this, but that also means that the process of using `meeting-agenda` style labels and then auto-generating the meeting issue is not possible with discussions.
