### ISSUE TITLE
OpenRFC Meeting - Wednesday, May 20, 2020, 2:00 PM EST

### ISSUE THREAD

**Issue by darcyclarke** [npm/rfcs#147]
## Why?
In our ongoing efforts to better listen to & collaborate with the community, we've started an Open RFC deep dive call that helps to move a specific conversation and/or initiative forward.

### Wednesday, May 20, 2020, 2:00 PM EST

**Cadence:**
This meeting is scheduled to take place **bi-weekly** alternating with our regular Open RFC calls. Previous meeting agendas and notes can be found [here](https://github.com/npm/rfcs/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed+label%3Ameeting)

**Add to your Calendar:**
You follow this & find other **npm** events by using our [public events calendar](https://calendar.google.com/calendar/embed?src=npmjs.com_oonluqt8oftrt0vmgrfbg6q6go%40group.calendar.google.com)

## What?

All discussions surrounding RFCs are covered by the [npm Code of Conduct](https://www.npmjs.com/policies/conduct). Please keep conversations constructive, civil & be mindful of when others are speaking. As is tradition, "raise your hand" when requesting to comment on a topic or request to comment asynchronously within the chat. The npm team may, at its own discretion, moderate, mute &/or remove a person from an Open RFC call for any reason.

### Invited Attendees
- *Anyone* interested in the idea of staging/stage publishes (please review the PRs beforehand)

### Agenda

1. **Housekeeping**
	1. Introduction(s)
	1. Code of Conduct Acknowledgement
	1. Outline Intentions & Desired Outcomes
	1. Announcements
1. Topic(s): 
1. **PR**: [#135 Clarify/Outline the RFC Withdrawal Process &amp; Amendment](https://github.com/npm/rfcs/pull/135)
1. **PR**: [#133 RFC: Remove --depth from npm outdated](https://github.com/npm/rfcs/pull/133)
1. **PR**: [#135 RFC: Add `npm-app-id` HTTP header](https://github.com/npm/rfcs/pull/138)
1. **PR**: [#144 RFC: npm diff](https://github.com/npm/rfcs/pull/144)
1. **PR**: [#146 RFC: Notification system for cli updates](https://github.com/npm/rfcs/pull/146)
1. **PR**: [#126 RFC: Adding types information to the Package JSON in the  registry](https://github.com/npm/rfcs/pull/126)
1. **PR**: [#18 RFC: audit resolve](https://github.com/npm/rfcs/pull/18)
1. **PR**: [#121 Added proposal for package version `link#[version]` syntax](https://github.com/npm/rfcs/pull/121)
1. **PR**: [#117 RFC: npm workspaces - Running Commands](https://github.com/npm/rfcs/pull/117)

## How?

**Join Zoom Meeting**
https://npm.zoom.us/j/914742332

Meeting ID: 914 742 332

One tap mobile
+16465588656,,914742332# US (New York)
+16699006833,,914742332# US (San Jose)

Dial by your location
        +1 646 558 8656 US (New York)
        +1 669 900 6833 US (San Jose)
Meeting ID: 914 742 332
Find your local number: https://npm.zoom.us/u/abR8OFljr8

**Comment by darcyclarke** [comment]
Meeting Notes Document: https://hackmd.io/wthHT81ZRS-tGnDOblYVwQ?both

**Comment by ruyadorno** [comment]
Video record: https://youtu.be/W6XbJ5e3xrA
