### ISSUE TITLE
It didn't work with ios8, ios7

### ISSUE THREAD

**Issue by varjose516** [npm/rfcs#164]
"buefy": "^0.8.20",
"vue": "^2.6.11"

The Vue app was not rendered in old ios versions if I added buefy to main.js

**Comment by ruyadorno** [comment]
hi @varjose516 I believe you posted your issue in the wrong place 😊 this repo is dedicated to discuss proposing changes to the [**npm cli**](https://preview-docs.npmjs.com/).

You can read more about the [RFC process here](https://github.com/npm/rfcs#whats-an-rfc).
