### ISSUE TITLE
Force:Source:Retrieve Apex Class not recognize sub-directories

### ISSUE THREAD

**Issue by vichpetr** [npm/rfcs#179]
Hi,

In our Org, we have split apex classes to sub-directories to better overview. After update to sfdx-cli to version 7.65.x (I have tried all available minor versions). All the classes are downloaded directly to the root classes folder and not respect the sub-directories (all older versions is respected that).

Could you please help me with that?

Thank you
Petr

**Comment by ljharb** [comment]
Seems like an issue with sfdx-cli and not with npm?

**Comment by vichpetr** [comment]
yes, probably wrong project - sorry. I will move it to the correct project.
