### ISSUE TITLE
Add registry identifier to publish prompt.

### ISSUE THREAD

**Issue by metaa** [npm/rfcs#191]
#96 introduced RFC `#28` for a publish confirmation prompt. I think that is really useful because it prevents a lot of accidental pushing.
I suggested [something similar](https://npm.community/t/npm-publish-dry-run-show-which-registry-the-package-will-go-to/2563) in the archived forums, but that never seemed to reach anyone.

However, my main concern with the current publishing process is, that it doesn't really let you know *which* registry you are publishing to. Faulty configuration or a typo in the publish command could lead to private / confidential code leaking into the public npm registry.

---

The current state of the RFC includes this line:
> This operation will publish your package to the npm registry.

I believe it should be made more obvious - or if it wasn't even intended to indicate it, specifically mentioned - that this line would show *which* registry it would publish to, if the user chose a custom registry.

## Example
```bash
npm publish --registry=https://example.com
```
> This operation will publish your package to the registry at https://example.com.

---

Please let me know what you think of this change.

**Comment by isaacs** [comment]
Adding that to the plan seems perfectly reasonable to me.  Can you open a PR to just edit the RFC file in the `accepted` folder?

**Comment by ruyadorno** [comment]
Already amended into the original [RFC0028](https://github.com/npm/rfcs/blob/3cf941cb22e6676b5e36d3e199b56bb7e652bab3/accepted/0028-publish-prompt.md), thanks @metaa ❤️
