### ISSUE TITLE
ℹ️ Cancelling Open RFC Call for Wednesday, September 30th, 2020

### ISSUE THREAD

**Issue by darcyclarke** [npm/rfcs#243]
We've been heads down shipping updates/improvements to the npm v7 beta over the last few months & today is no different. Our team's hope is to cut a release candidate & open a PR against Node.js 15 / master by EOD today. With that in mind though, we've decided to cancel today's Open RFC call & will get back to our normal cadence next week (Wednesday October 7th).

**Comment by ruyadorno** [comment]
heads up @ljharb @wesleytodd @Christian24 @bnb 😁

**Comment by bnb** [comment]
Thanks for the ping, I was feeling bad since I was going to have to miss it today - now that's not a problem 😅

**Comment by Christian24** [comment]
Thanks for the ping, I wouldn't have been able to update my RFC in time anyway, so I used the time now to do that. :) Good luck on the RC.
