### ISSUE TITLE
[RRFC] `registry:<url>#<name>[@<version-range>]` dependency specifier

### ISSUE THREAD

**Issue by isaacs** [npm/rfcs#275]
## Motivation ("The Why")

There are cases where it's useful to fetch a package from a given registry, without setting the `--registry` config to that other registry for all packages in the command context.

#### Mixed Internal/External Stuff

`@my-scope/foo` should come from the public npm registry.  Everything else in the `@my-scope` scope should come from our internal registry.  Additionally, the (unscoped) `my-company-project` should come from our internal registry.

`.npmrc` file:

```ini
@my-scope:registry = https://my-company-private.registry.internal
```

`package.json` file:

```js
{
  "dependencies": {
    "@my-scope/bar": "1.2.x", // internal registry
    "@my-scope/baz": "^4.2.1",  // internal registry
    "@my-scope/foo": "registry:registry.npmjs.org:@my-scope/foo@2.x", // public registry
    "my-company-project": "registry:my-company-private.registry.internal:my-company-project@^8.3.0" // internal
  }
}
```

#### Copying from One Registry to Another

This would be a pretty sweet way to do that:

```
npm publish --registry=https://registry.internal foo@registry:registry.npmjs.org:foo@1.2.3
```

### Challenges and Hazards

- New specs always split the ecosystem.  Could we insist that we don't publish anything with a `registry:` specifier unless it has a `"engines": { "npm": ">=7.whatever.version.implements.this" }`, so that at least earlier clients break in a cleaner way?
- Has to be threaded through _everything_ that uses `npm-package-arg`.
- Can we dedupe `foo@registry:blah:foo@1.2.3` against `foo:registry:otherone:foo@1.2.3`?  Are they "the same"?  (Note that we _will_ dedupe if they're actually the same bits, regardless of where they come from, so maybe this isn't an issue, but could we go further if we don't have an integrity for one of them, and say they're the same because name/version match?)
- What about `foo@registry:registry.npmjs.org:bar@2.3.4`?  Should we not allow the name to be swapped?  Or does this end up becoming another form of `foo@npm:bar@2.3.4`?
  - If you _can_ swap the name, is that good?  It might be good.
  - If you _can't_ swap the name, should we even have it there?  Maybe `foo@registry:registry.npmjs.org@1.2.3` is enough?
- Maybe `foo@registry:registry.npmjs.org@1.2.3` is fine, even if we do let you swap the name?  Just infer that it's the same name we already have to the left of the first `@` sign?
- Is this too presumptuous for package authors to specify?  Ie, maybe the user should have way to say "no, get this from my registry, not from the public registry, no matter what"?  (Note: authors _already_ can be presumptuous in this way by specifying a tarball target, but it's inconvenient and power-user-y enough that most don't do that.)

### References

* Related to #217

**Comment by isaacs** [comment]
Maybe should make the registry/pkg@version separator `#`, since `:` will show up in the url?  Then we could also put the protocol in there, instead of forcing it to be `https`.  Ie, instead of 

```
registry:registry.npmjs.org:express@latest
```

it'd be:

```
registry:https://registry.npmjs.org#express@latest
```

This is much easier to parse if the url has a `:` in it, like:

```
registry:http://internal-registry:1234/some/path#express@latest
```

because we can just strip off the url and get all the bits we care about:

```
const { URL } = require('url')
const spec = 'registry:http://internal-registry:1234/some/path#@internal-scope/express@latest'
const parsed = new URL(spec.substr('registry:'.length))
const pkgSpec = parsed.hash.substr(1)
parsed.hash = ''
const registry = parsed.href
console.error({ registry, pkgSpec })
/*
{
  registry: 'http://internal-registry:1234/some/path',
  pkgSpec: '@internal-scope/express@latest'
}
*/
```

**Comment by isaacs** [comment]
Current status:

- Consensus around `registry:<url>#specifier` approach.  Need to update RFC to that format.
- This is a mere typing problem implementation-wise, albeit a significant one.  Once ratified, we'll need to make sure to carefully comb through all the places where we use `npm-package-arg` specifiers, and update them to handle aliases properly, fetch from the correct registries, etc.  (Main areas to address: arborist, pacote, npm-registry-fetch, and cli.)

**Comment by ruyadorno** [comment]
RFC: https://github.com/npm/rfcs/pull/314
