### ISSUE TITLE
[QUESTION] Alternative for $npm_package_* to pass multiple parameters to node

### ISSUE THREAD

**Issue by dandv** [npm/rfcs#305]
## Motivation ("The Why")
In my `package.json`, I have several scripts that call `node` with the same parameters over and over. To simplify that invocation, I've created a package.json variable, and am invoking the scripts like this:

```json
{
  "nodeParams": "--experimental-specifier-resolution=node --harmony -r source-map-support/register",
  "scripts": {
    "dostuff": "node $npm_package_nodeParams myscript.js"
  }
}
```

This is quite common for calling compiled TypeScript code, but no longer works in v7 due to RFC21. However, [I can't find what the recommended alternative is](https://github.com/npm/cli/issues/2452).

I picked up this idea from somewhere on StackOverflow, so I'm probably not the only one impacted by the change.

**Comment by ivpcode** [comment]
hi, same issue.

**Comment by artischockee** [comment]
Same issue. I used to retrieve data from `author.name` field (in `$npm_package_author_name` env variable) and it was being revealed in my app. But, perhaps starting from this "RFC21", this variables is not showing at all, giving the consumer an empty string.

**Comment by isaacs** [comment]
You can put these values in a `config` block in `package.json`, like this:

```json
{
  "config": {
    "nodeParams": "--experimental-specifier-resolution=node --harmony -r source-map-support/register",
    "author": {
      "name": "Wile E. Coyote"
    }
  },
  "scripts": {
    "dostuff": "node $npm_package_config_nodeParams myscript.js",
    "whoami": "echo $npm_package_config_author_name"
  }
}
```

Passing the entirety of `package.json` into the environment was contributing to problems, because sometimes these files contain a _lot_ of stuff, including very long strings that blew up the environment size.  (We were also passing every last config value, even those set at the default value, so that was also adding to the problem.)

**Comment by wu-lee** [comment]
Thanks - this mechanism also provided access to parameters from the .npmrc file(s). What is the recommended forward and backward compatible way of getting access to those again?

Also, this information is not easy to find. See https://github.com/npm/cli/issues/2452#issuecomment-1028142496
