### ISSUE TITLE
[RRFC]  --registry support for custom init modules

### ISSUE THREAD

**Issue by hemanth** [npm/rfcs#378]
- [x] Search for an existing/duplicate RRFC which might be relevant to your RRFC

## Motivation 

We normally have situations where we are using proxy for our npm registers, `npm install` provides `--registry` option so that we can provide the requires registry URL.

The same should be possible for `npm init` and `npx` 

### Example

```
npm init --registry=https://registry.npmjs.org/ <module>
```

```
npx --registry=https://registry.npmjs.org/ <module>
```
#### Current Behaviour

`--registry` is not respected.

#### Desired Behaviour

`--registry` should be respected.

### References

* n/a

**Comment by ljharb** [comment]
It seems reasonable that `npm init`, with a package arg, accepts all the same arguments `npm install` and `npx` do?

**Comment by isaacs** [comment]
If what you describe is true, then this sounds like it is not an RFC, it's just a bug.

Can you describe more about your use case where it's not working?  I have verified that the `--registry` config is indeed respected and used by init and exec, and the `--proxy` config is as well.

- What error are you encountering?  (Ie, how do you know that `--registry` is not being respected?  What would it look like if it was respected?)
- How are your proxies configured?  (Are they HTTP proxies, or generic SOCKS5 network proxies?)
- For the purposes of the npm CLI, are they HTTP _proxies_, or are they different registries that proxy the _contents_?  (Ie, do you do `npm init --registry=http://local-proxy-server/` or do you do `npm init --registry=https://registry.npmjs.org/ --proxy=http://local-proxy-server/`?)

**Comment by hemanth** [comment]
@isaacs I had created a [bug](https://github.com/npm/cli/issues/3226) and closed it thinking this is a potential RFC, as `npm init --help` didn't mention about `--registry` or `--proxy`

**Comment by isaacs** [comment]
Ok, well, it looks like you have a `proxy` config set in your npm environment, and that proxy is not reachable.  The error message could be improved, but it is "respecting" the registry config, it's just trying to reach it through the proxy you have configured.  Every http request will go through that proxy if it's configured.

I think the bug here is just the error message being less helpful than it could be.
