### ISSUE TITLE
ℹ️ Cancelling Open RFC Call for Wednesday, May 26th, 2021

### ISSUE THREAD

**Issue by darcyclarke** [npm/rfcs#385]
Apologies for the last minute note; Our team is taking another week off from the Open RFC call as we've been heads down tackling user feedback & finishing off our next set of workspace improvements. 

Of note, our team will also be joining the community next week for [OpenJS World](https://openjsf.org/openjs-world-2021/) so we'll preemptively be cancelling next week's call.

If you haven't already upgraded - we released [`v7.14.0`](https://github.com/npm/cli/releases/tag/v7.14.0) last Thursday which came with it a ton of new subcommands that have become "workspace aware" (including `install`, `uninstall`, `update` & more); As usual, we'll be cutting another release tomorrow & you can always get the latest `npm` via `npm i -g npm`.

**Comment by naugtur** [comment]
Thanks and see you on openJS world
