### ISSUE TITLE
[RRFC] [FEATURE] `publish` should have option to silence errors about already published versions

### ISSUE THREAD

**Issue by cinderblock** [npm/rfcs#387]
## Motivation ("The Why")

I want an idempotent way to run `npm publish`

### Example

CI not erroring if a version is already published: `npm publish --ignore-existing`

#### Current Behaviour

If you run `npm publish` on an already published version, there is no way to silence and ignore errors without extra shell operations. For instance, `npm publish 2>&1 > /dev/null || :`

#### Desired Behaviour

A simple command line option for `npm publish` that doesn't produce a non-zero exit code if the package (at the `package.json#version` specified version) has already been published.

Something like `npm publish --ignore-existing --silent` should both not have an error exit code and not print any output.

### References
https://github.com/npm/cli/issues/1559

**Comment by naugtur** [comment]
It'd be sufficient to check the exit code. Have you tried checking if the exit code differs depending on the reason of the failure?

**Comment by cinderblock** [comment]
Yes, it's possible to check exit code with shell features or an extra wrapper script. IMHO, this should not be the required way to interface with common outcomes of `npm publish`.

**Comment by lukekarrys** [comment]
Thanks for this RRFC. A feature that would handle (https://github.com/npm/rfcs/issues/466) was discussed and agreed to on 2021-09-29 (https://github.com/npm/rfcs/blob/main/meetings/2021-09-29.md#issue-466-rrfc-npm-publish---if-needed---ljharb), so I'm going to close this one.
