### ISSUE TITLE
[RRFC] <title>

### ISSUE THREAD

**Issue by O-Asymmetricity-O** [npm/rfcs#404]
## emails of contributors

https://registry.npmjs.org/discord.js

im not sure if its an issue or everyone knows your email is shown when contributing to a npm package 

but if follow the link it shows the email of  every contributor 

```json
{"shasum":"9a3be3d3348b1f7b6efc729e88368d664bdd1d3d","tarball":"https://registry.npmjs.org/discord.js/-/discord.js-2.6.4.tgz"},"maintainers":[{"name":"hydrabolt","email":"amishshah.2k@gmail.com"}],"directories":{},"deprecated":"no longer supported"},"2.6.5":{"name":"discord.js","version":"2.6.5","descr```

**Comment by bnb** [comment]
this is how publishing works, and is a non-issue. Your email is also shown on every git commit, too 😅
