### ISSUE TITLE
[RRFC] Add a way to define the `versioning` specification in `package.json`

### ISSUE THREAD

**Issue by j-m** [npm/rfcs#448]
## Motivation ("The Why")

All too often I install packages which later catch me out by releasing a breaking change on what we assume is a `minor` version bump.   
As it stands, `npm` assumes that all packages follow `semver` so long as it follows the x.y.z format, and that simply isn't true; for example, even a package as popular as `typescript` doesn't follow `semver`.   
If we introduce a `versioning` property to `package.json` we can let the authors of the package specify whether their package follows `semver` or something else.   
Then, when I install that package, `npm` can automatically `--save-exact` if `versioning` is anything but `"semver"`.  

### Example

For now we can keep this simple, if `versioning` is set to `"semver"` then install that package with `--save`. If `versioning` is set to anything else (perhapse we suggest `"custom"` or something for consistency) then install the package with `--save-exact`.
Additionally, we should allow developers to specify the `"version"` property as they please (i.e. not semver format) if `"versioning"` is set to anything but `"semver"`.

In future we may wish to add extra options which is why I didn't suggest a `"semver": "false"` property. For simplicity, it may be better to define a versioning accuracy, i.e. `"*"` (any, latest), `"^"`, `"~"`, `"="` (exact). 
For example, `typescript` can be installed with `~`. 

#### Current Behaviour

Packages may not be following semver so every developer who installs a package has to check whether that package is semver when, realistically, the developers should be able to set something and the whole version accuracy/bumping be done automatically. 

Also asking for a developer to clarify their versioning is akward and time consuming; a surprising number of packages don't mention how they version.

#### Desired Behaviour

To just be able to `npm install` any package without worrying about whether that package is following semver.
So when I install `typescript`, npm will install an exact version. 

### References

* n/a

**Comment by j-m** [comment]
Whoops, missed #349, should I close this?

**Comment by darcyclarke** [comment]
@j-m yes please; notably though, our team has commented about this kind of behaviour in the past & did not think there was a net benefit in changing the current default: https://github.com/npm/rfcs/pull/40#issuecomment-521033284

**Comment by j-m** [comment]
I completely agree with those comments.

However, I still think it'd be worth adding a way for developers to specify whether their package should be installed with *, ^, or ~; security and dedupe wise I can see now why = would be a bad idea.
