### ISSUE TITLE
📊 Poll: new name for the proposed reification strategy (RFC #436)

### ISSUE THREAD

**Issue by darcyclarke** [npm/rfcs#454]
This is a poll to help determine the sentiment around different names for RFC #436; We believe the following are good alternative options that navigate away from the current "pure mode" nomenclature. We are open to other suggestions from the community if you'd like to share them in this thread. 

We'll keep this open for roughly a week & discuss the results in our Open RFC calls.

[![](https://api.gh-polls.com/poll/01FFFREBNQQ17Y7G090SA44DVY/Isolated)](https://api.gh-polls.com/poll/01FFFREBNQQ17Y7G090SA44DVY/Isolated/vote)
[![](https://api.gh-polls.com/poll/01FFFREBNQQ17Y7G090SA44DVY/Strict)](https://api.gh-polls.com/poll/01FFFREBNQQ17Y7G090SA44DVY/Strict/vote)
[![](https://api.gh-polls.com/poll/01FFFREBNQQ17Y7G090SA44DVY/Linked)](https://api.gh-polls.com/poll/01FFFREBNQQ17Y7G090SA44DVY/Linked/vote)

**Comment by isaacs** [comment]
Might want to add an option for "unhoisted", but I like how "isolated" specifies the effect rather than the implementation.

"Strict" is sort of overlapping with the `strict-peer-deps` config flag, so it might carry some unwanted connotations.

**Comment by isaacs** [comment]
Also `'use strict'` in js code and the `--use-strict` node arg (which are two different things).

**Comment by darcyclarke** [comment]
Closing this poll; We've decided to rename the RFC/mode to "Isolated". Thank you to everyone that shared their input/perspectives here & on our call today.
