### ISSUE TITLE
[RRFC] npm outdated (npm >= 7.24.2) exit with incorrect status code

### ISSUE THREAD

**Issue by nassau-t** [npm/rfcs#473]
## Motivation ("The Why")

npm v8.0.0 (included in node v16.11.0) has an exit status code of 1 when there are outdated packages.

By convention, exit status code must be 0 if there is no execution error.
And can be in the range 1-255 if there is an execution error (network, disk, internal error...)

But it has been replaced with a particular behaviour that has no sense with the above convention. Actual behaviour is:
exit status code 0 -> there aren't outdated packages
exit status code 1 -> there are outdated packages.

So this behaviour creates a problem if npm outdated is executed from a any program, because the program throws an error exception.

### Example

From a node.js program, I get the error of the catch block, when from cmd npm outdated show no error, only the list of outdated packages.

```
C:\temp>node
Welcome to Node.js v16.11.0.
Type ".help" for more information.
> try {
...   let result = require('child_process').execSync('npm outdated -g --depth=0');
...   console.log('ok');
... } catch (err) {
...   console.log('error');
... }
error
undefined
> .exit

C:\temp>npm outdated -g --depth=0
Package             Current   Wanted   Latest  Location                         Depended by
@types/node         16.10.2  16.10.3  16.10.3  node_modules/@types/node         global
eslint               7.32.0    8.0.0    8.0.0  node_modules/eslint              global
webpack-dev-server    4.3.0    4.3.1    4.3.1  node_modules/webpack-dev-server  global
```

#### Current Behaviour

So it seems that npm outdated has a status exit code of 0 if there aren't outdated packages.
And a status exit code of 1 if there are outdated packages.

#### Desired Behaviour

1. npm outdated should have a status exit code of 0 if there haven't been an error (network, disk, internal error...).
    1.1. If stdout return an empty string, there aren't outdated packages.
    1.2. If stdout have a non empty string. there are outdated packages.
2. npm outdated should return a status exit code of 1 if there have been an error (network, disk, internal error...).

Examples of 1.1. and 1.2., you know that npm outdated has ended ok, and there is very simple to know if there are outdated packages or not.

Example of 1.1.: Execute ok, there are no outdated packages.

```
$ result=$(npm outdated -g --depth=0); echo $?; echo "*$result*"
0
**
```

Example of 1.2.: Execute ok, there are outdated packages.

```
$ result=$(npm outdated -g --depth=0); echo $?; echo "*$result*"
0
*Package             Current   Wanted   Latest  Location                         Depended by
@types/node         16.10.2  16.10.3  16.10.3  node_modules/@types/node         global
eslint               7.32.0    8.0.0    8.0.0  node_modules/eslint              global
webpack-dev-server    4.3.0    4.3.1    4.3.1  node_modules/webpack-dev-server  global*
```

### References

* Java 7 docs
https://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html#exit(int)
public void exit(int status)
The argument serves as a status code; by convention, a nonzero status code indicates abnormal termination.

* Python 3 docs
https://docs.python.org/3/library/sys.html#sys.exit
zero is considered “successful termination” and any nonzero value is considered “abnormal termination” by shells and the like. Most systems require it to be in the range 0–127, and produce undefined results otherwise. Some systems have a convention for assigning specific meanings to specific exit codes, but these are generally underdeveloped; Unix programs generally use 2 for command line syntax errors and 1 for all other kind of errors.

* The Linux Documentation Project
https://tldp.org/LDP/abs/html/exitcodes.html
Exit Code Number 1
Meaning	Catchall for general errors

* Unix and linux system administration handbook 5. Evi Nemeth, Garth Snyder, Trent R.Hein, Ben Whaley, Dan Mackin.
init (or systemd) also plays another important role in process management. When a process
completes, it calls a routine named _exit to notify the kernel that it is ready to die. It supplies an
exit code (an integer) that tells why it’s exiting. By convention, zero indicates a normal or
“successful” termination.

* Modern Operating Systems 4th Edition. Andrew S. Tanenbaum.
It has one parameter, the exit status (0 to 255), which is returned to the parent in the variable status of the waitpid system call. The low-order byte of status contains the termination status, with 0 being normal termination and the other values being various error conditions.

**Comment by nassau-t** [comment]
I didn't know that I could attend the meeting. Anyway, I don't think anything would have changed. Things have to be discussed before the meetings.

The change in 7.27.2 was to return to a bad behaviour, so it should be avoided. v7 was a new big version, so it was a great moment to do that.

As I have show in the code above, I can use my execAsync to escape from that bad behaviour. I think that you could done something similar in your code (I try it and post in this rfc, and it isn't difficult to catch if a command return results or not).
I was not thinking on me in this rfc. I was thinking in the future of npm and in fulfill with standards.

**Comment by lukekarrys** [comment]
As was discussed in the RFC Meeting on 2021-10-13 (https://github.com/npm/rfcs/blob/main/meetings/2021-10-13.md#issue-473-rrfc-npm-outdated-npm--7242-exit-with-incorrect-status-code---nassau-t) this is working as intended. I plan to document this as part of the doc we discussed in the `2022-02-23` meeting around npm ideologies with output and logging.

**Comment by kmturley** [comment]
I agree this is really odd behavior...

Use-case:
- Install package if it is not already installed
- Upgrade package if it is outdated

```
// check whether the package is installed
npm list my-package -g --json

  // if not installed then install it
  npm install my-package -g --json

  // else check if package is outdated
  npm outdated my-package -g --json

     // if out-of-date then update
     npm update my-package -g --json
```

This logic breaks at `npm outdated` because the script Exit code is 1

@nassau-t solution is a good workaround to make it work!

**Comment by ljharb** [comment]
It doesn’t make sense to run outdated globally; there’s no package.json to check.

**Comment by kmturley** [comment]
I have removed the global flags from the example code, the use-case still stands

**Comment by omidantilong** [comment]
@nassau-t thankyou for the suggested workaround - this behaviour was driving us absolutely nuts. After reading through this thread I can see the logic from both sides but I completely agree that sending a failure code when the command has executed successfully is _very_ confusing. 

 It would be great if this could be made configurable somehow.

**Comment by AndreCunha1** [comment]
My scripts also broke and finally I found out why ☹️

Back in programming classes, I was taught that return exit code != 0 means execution error (which "proves" nothing, of course). Successfully reporting outdated packages does not seem like an execution error to me.

I like the suggested opt-in approach of a parameter (e.g. `--ownExitCodes` or whatever name fits best) to control this behavior.

PS: `npm audit` also has this same behavior and, although it is documented, should probably be considered together with `npm outdated` for consistency. Maybe there are more commands with similar behavior.

**Comment by ljharb** [comment]
@AndreCunha1 that's never been the case; for example, `ls` or `grep` return nonzero when they don't find a match, which is a successful execution that didn't find anything.

**Comment by AndreCunha1** [comment]
@ljharb this was already mentioned by @iarna [here](https://github.com/npm/rfcs/issues/473#issuecomment-942570920) and it did not change my opinion.

**Comment by ljharb** [comment]
Of course you are entitled to your opinion on what is better, but what you were taught is objectively incorrect because of the existence proof of these other tools. The mental model of exit codes is "what programs DO" and not "what people think programs SHOULD do", and it's important for npm to fit the prevailing mental model.

**Comment by nassau-t** [comment]
I opened this issue, and I think I sufficiently motivated it, citing bibliography. So, it's not only my opinion. Still I think @AndreCunha1 is right.
@ljharb "objectively incorrect" is really "completely subjective": It's like justifying drug use because there are people who use drugs. And this isn't "what programs DO" neither "what people think programs should do". It's a convention on how programs should work.

**Comment by AndreCunha1** [comment]
> "what you were taught is objectively incorrect because of the existence proof of these other tools"

So anything can be proven incorrect by writing a tool that does otherwise?

Note that I am not implying that what I was taught is correct either, hence my previous "proves nothing" there.

Anyway, I am happy to find the cause of my broken scripts and have already adjusted them. Another successful outcome of this discussion could be to simply update the `npm outdated` documentation to explain this behavior, just like the documentation of `npm audit` already does.

**Comment by wallyhall** [comment]
I might be missing the obvious here - but is a (what seems to me perfectly reasonable middle-ground) straightforward option not to continue returning 1 if outdated packages are found, _but to ensure any error scenario is >1_?

Certainly, for us, we want (and arguably _need_) to validate if a problem occurred.  I mind if the exit code is either 1 or 0 for success, provided non-success is distinguishable.

**Comment by chrillep** [comment]
run `npm outdated || true` and it will always return exitcode 0 ?

**Comment by xavierfoucrier** [comment]
After trying a lot of things, I came to the same conclusion as many peoples in this thread: use a custom `Promise` base handler instead of trying to `promisify` the `exec` method. Using `|| true` is also a good alternative as the method always return json / empty json. Sad to says that returning 1 as error code when there are outdated dependencies is clearly the right way to manage error code in programs.

I guess there could be an alternative with some arguments to the `npm outdated` method and I hope in a near future to see more flexibility on this.

😎

**Comment by tiennou** [comment]
`npm outdated --json || true` doesn't work if I'm interested in the *output*, since that will cause `execSync` to barf out an error and never provide me with the JSON.

And I can't fathom switching to the promisified-exec variant, because the code I'm in is *sync* code, and adding async to it would need me to recolor all the functions I'd be calling it from.

My suggestion would be to add an `npm outdated --check` that returns 1 if there's outdated dependencies and no output, for the tooling that wants the check done, then make the non-check cases return 0 unless there's an actual *problem* reporting the outdatedness (like network failure, or invalid package.json), as a user typing the command on their terminal doesn't exactly care about the error status.
