### ISSUE TITLE
Open RFC Meeting - Wednesday, Sept 4th @ 12:00pm EST

### ISSUE THREAD

**Issue by darcyclarke** [npm/rfcs#49]
Hi folks!

We've been considering better ways to interact with the community to ensure that there is movement on the important issues/ideas that are being brought up here. We've landed on trying out a bi-weekly, potentially monthly, meeting that is open to anyone that would like to attend.

Similar to the [Node](https://github.com/nodejs/TSC/blob/master/WORKING_GROUPS.md) & [OpenJS](https://github.com/openjs-foundation/) foundation WG meetings, we'll be looking to source our agenda from existing issues & open PRs from this repository. Going forward, the agenda should be posted *a week before* the meeting to give everyone time to suggest talking points & express interest on attending. 

## Does this change the RFC Process?
This meeting does not change the [existing RFC process](https://github.com/npm/rfcs/#npm-rfc-process) or ratification criteria.

## When will this take place?
The first meeting will be taking place on: **Wednesday, September 4th @ 12:00pm EST**

## What is on the agenda?
This agenda is based on the current open issues/PRs. Feel free to comment if you'd like a topic to be added: 

- #43 Peer dependencies installation
- #47 Unlisted dependency support
- #48 Link .hook scripts
- #27 Package overrides
- #36 Script-shell config
- #1 Display package size information postinstall
- [`sustainability`](https://github.com/npm/cli/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc) & [`support`](https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/PACKAGE-SUPPORT.md) drafts

## How can I join?

**Join Zoom Meeting**
https://npm.zoom.us/j/584504445

**Dial by your location**
+1 669 900 6833 US (San Jose)
+1 646 558 8656 US (New York)

**Meeting ID:** 584 504 445
Find your local number: https://zoom.us/u/abR8OFljr8

**Comment by wesleytodd** [comment]
What is the plan for length of this meeting?  This seems like a very long agenda for a single hour.  Is this planned to be the first of many meetings to discuss these RFC's?

**Comment by darcyclarke** [comment]
@wesleytodd meeting is currently scheduled for an hour & we can discussed cadence toward the end based on what we can get through. The current intent is a monthly meeting but that could change if we think there's enough to be doing a bi-weekly

**Comment by darcyclarke** [comment]
Thank you to everyone that joined today! ❤️ We're looking forward to making this a regular call & it's great to see early support of that.

For reference, here is the link to the [Meeting Notes](https://docs.google.com/document/d/1a8XFB_r7cNnexNm9peBvqpZwojNDiHYYbkSpsDZ4jnw/edit). You can follow up to any discussion by creating an issue in this repo &/or commenting on the specific RFC PR.

**Comment by feross** [comment]
Bummed I missed this. When is the next meeting?

**Comment by darcyclarke** [comment]
@feross we'll try to have a more timely cadence going forward. The next meeting is currently scheduled for [Wednesday October 2nd @ 1:00pm ET](https://github.com/npm/rfcs/issues/52)

**Comment by abunaif1** [comment]
Iosxmax.com

**Comment by Lucky100577** [comment]
Sent to you Lizaschryer
