### ISSUE TITLE
[RRFC] hoisting dvDependencies of workspaces

### ISSUE THREAD

**Issue by eng-dibo** [npm/rfcs#491]
running `npm install` on a monorepo that has a `workspaces` property in its `package.json` hoisting each workspace's dependencies to the root unless a conflict detecting. but that doesn't go with devDependencies, some devDependencies (not all) are installed inside the workspace and not hoisted even if no conflicting, but I don't know why?

is there an option to hoist **all* devDependencies too?

**Comment by darcyclarke** [comment]
This sounds like a bug; can you please file it against [npm/cli](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+8.x&template=bug_8.yml&title=%5BBUG%5D+%3Ctitle%3E)
