### ISSUE TITLE
ℹ️ Cancelling Open RFC Calls for Wednesday, Dec. 1st & 8th

### ISSUE THREAD

**Issue by darcyclarke** [npm/rfcs#498]
Apologize for the last minute notice; our team has conflicting calls for the next two weeks which means we won't be able to run our normal Open RFC calls. We'll continue to discuss RFCs async though & hopefully make progress in the issues/prs themselves. 

Notably, the last call we'll do this year (2021) will be **Wednesday December 15th**. Our team will then be taking some much needed time off before getting back into the swing of things in the New Year (beginning calls again on **Wednesday January 12th**)

If you missed the last call, you can [watch the recording](https://youtu.be/Y4-V8vG3wxc) or read the [meeting notes](https://github.com/npm/rfcs/blob/main/meetings/2021-11-24.md). Also, if you haven't already - you can update to the latest release of the CLI ([`v8.1.4`](https://github.com/npm/cli/releases/tag/v8.1.4)) in the normal ways (ie. `npm i -g npm`).

**Comment by ljharb** [comment]
@darcyclarke January 15th is a Saturday; do you mean Wednesday the 12th, or the 19th?

**Comment by darcyclarke** [comment]
@ljharb thanks for this catch, it should be **January 12th**
