### ISSUE TITLE
Enforce flags for publishing npm packages to public repositories for the first time

### ISSUE THREAD

**Issue by sedoy26** [npm/rfcs#535]
### Discussed in https://github.com/npm/rfcs/discussions/534

<div type='discussions-op-text'>

<sup>Originally posted by **Alirun** February 18, 2022</sup>
Hey there

I'm wondering, why is it possible to publish new package into public repository without any confirmation in first place?

I get that `npm publish` is very handy, and it's ok for it to work as is, by why only scoped packages are being checked at the first publish?

Also a question, why don't include `"private": true` into every generated `package.json` by default?
I think that if you need to explicitly remove this line, it's convenient and is much safer and better, than not having it in by default at all.</div>

**Comment by darcyclarke** [comment]
Hey there! We actually have an accepted RFC for "publish prompts" which should handle this usecase where someone wants to gate the initial publish with some kind of confirmation (ref. https://github.com/npm/rfcs/blob/main/accepted/0028-publish-prompt.md).

<div type='discussions-op-text'>

<sup>Originally posted by Alirun February 18, 2022</sup>
_"why only scoped packages are being checked at the first publish?"_
</div>
&nbsp;

In terms of the default template used for creating packages with `npm init`, you can switch this by running `npm config set init.module <pkg>`; this will define a different package to be used which could have a default `private: true` value in the `package.json` if you want; or any number of changes/deviations.
