### ISSUE TITLE
[RRFC] `npm update` update denpendecy semver in package.json by default

### ISSUE THREAD

**Issue by HomyeeKing** [npm/rfcs#540]
### Example

```json
foo: "^0.1.1"
```
foo@latest -> 0.1.3

exec `npm update foo`
```json
foo: "^0.1.3"
```

#### Current Behaviour

we need to add `--save` option now which is verbose, also `npm update` not support update the `devDependencies` 

#### Desired Behaviour

there're two solution:
- `npm update`, update both `dependencies` and `devDependencies`
- update `denpendencies` only and `-D or --save-dev` update `devDependencies`

by the way, the above has already implemented by `npm install`, so we can also update dependencies by `npm installl` 

### References

* n/a

**Comment by wraithgar** [comment]
the `--save` flag for update was implemented in `v8.3.2` https://github.com/npm/cli/pull/4223
