### ISSUE TITLE
What time should we run the Open RFC calls?

### ISSUE THREAD

**Issue by darcyclarke** [npm/rfcs#55]
# What?
We're looking to try and widen the audience that attends our [Open RFC calls](https://github.com/npm/rfcs/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed+label%3Ameeting) and want to suggest a few other options for the time of day it takes place (currently the next call is scheduled for **Wednesday, October 30th @ 1pm ET**). 

Please select what you think would be the ideal time for you to attend based on the following options:

[![](https://api.gh-polls.com/poll/01DQY35Y78HS5XAV0V3F6Y0PHZ/11am%20ET)](https://api.gh-polls.com/poll/01DQY35Y78HS5XAV0V3F6Y0PHZ/11am%20ET/vote)
[![](https://api.gh-polls.com/poll/01DQY35Y78HS5XAV0V3F6Y0PHZ/12pm%20ET)](https://api.gh-polls.com/poll/01DQY35Y78HS5XAV0V3F6Y0PHZ/12pm%20ET/vote)
[![](https://api.gh-polls.com/poll/01DQY35Y78HS5XAV0V3F6Y0PHZ/1pm%20ET)](https://api.gh-polls.com/poll/01DQY35Y78HS5XAV0V3F6Y0PHZ/1pm%20ET/vote)
[![](https://api.gh-polls.com/poll/01DQY35Y78HS5XAV0V3F6Y0PHZ/2pm%20ET)](https://api.gh-polls.com/poll/01DQY35Y78HS5XAV0V3F6Y0PHZ/2pm%20ET/vote)

Depending on the results, we may decide to follow up with a different poll for days & times if we don't see a lot of consensus. 

As always, feedback is welcome/appreciated!

**Comment by darcyclarke** [comment]
- [x] Updated the next meeting in the [`npm - Public Events` calendar](calendar.google.com/calendar/embed?src=npmjs.com_oonluqt8oftrt0vmgrfbg6q6go%40group.calendar.google.com) event accordingly
- [x] Closing this issue and will make a new poll for scheduling an alternating day/time

**Comment by ljharb** [comment]
@darcyclarke that calendar link 404s for me

**Comment by darcyclarke** [comment]
@ljharb sorry about that 😔 ... try this: https://calendar.google.com/calendar/embed?src=npmjs.com_oonluqt8oftrt0vmgrfbg6q6go%40group.calendar.google.com
