### ISSUE TITLE
[RRFC] improving the workspaces symlinking experience

### ISSUE THREAD

**Issue by bnb** [npm/rfcs#556]
## Motivation ("The Why")
Personally as I began working with workspaces, one of the most confusing concepts was how to actually access one module from another. I've also heard this from other folks - extremely skilled engineers - I've talked to who were trying to pick up workspaces, prior to me using them. Upon reaching out to folks that I think most others wouldn't have available to them, I was able to understand that the modules were symlinked from node_modules. Great!

The one pain point with that is that it's not entirely obvious what the "correct" way to do this is. Sometimes it works magically, but other times it doesn't. This seems to be because this symlinking feature is hidden behind `npm install`, either at the root or in the new workspace you want to add (`npm install -w myspace`).

I'd like to request that this be improved in _some_ way. Here are the ways I've thought of:
- triggering symlinking more often: when i `npm i -w lol`, symlink `lol`. I assume this has to do with Arborist, so I'm not sure what the simplest way to do this is but ideally taking whatever path has the least perf impact would be ideal.
- manually triggering symlinking: I can think of cases where a manual trigger outside of `npm install` might be useful (people who want to manually do everything, external tooling that does it but not the linking). `npm ws link` or something like that.

#### Current Behaviour
```bash
npm init -w myspace
npm install # it's unexpected that I have to do this!
```

#### Desired Behaviour
```bash
npm i -w myspace # automatically links on init!
```

```bash
npm ws link # links all workspaces!
npm ws link myspace # just links myspace!
```

### References
* n/a

**Comment by ljharb** [comment]
"linking myspace" is a very old-fashioned phrase

I think `npm ws link [foo]` makes a ton of sense.

**Comment by ruyadorno** [comment]
@bnb did you mean `npm init -w myspace` instead of `npm i -w myspace` in the current/desired examples?

**Comment by bnb** [comment]
going to close this since it's been implemented :)
