### ISSUE TITLE
[RRFC] Allow changing a package version's tag after publish

### ISSUE THREAD

**Issue by Dionysusnu** [npm/rfcs#562]
## Motivation ("The Why")

Developers might make mistakes or want to change a tag for other reasons, which is not breaking for package versions. This should be allowed.

### Example

I normally publish development releases for my package with the `@next` tag. This way normal install users will get stable releases.
However, I accidentally published a development release without the tag, meaning it is now on the `latest` tag. I want to change the tag, so that the version is public on the `next` tag, and the `latest` tag goes back to being my latest stable release. I could not find documentation for any current way to do this. I would rather not unpublish the dev version, because it does have users, and I'm not sure the unpublish policy would even let me.

#### Current Behaviour

This currently seems to be impossible. Running `npm publish` again gives a 403 error:
`You cannot publish over the previously published versions: <the version the developer tried to change the tag of>`

#### Desired Behaviour

Changing the tag of a published version will be possible, by re-running the publish command, specifying the new intended tag. This may need a `--change-tag` override to prevent accidentally re-publishing a version when the developer meant to publish a new version.

### References

* n/a

**Comment by arcanis** [comment]
https://docs.npmjs.com/cli/v8/commands/npm-dist-tag

**Comment by Dionysusnu** [comment]
No, actually, that didn't work. These are the commands I did:
- `npm dist-tag add thepackage@futureversion.0.0-dev-commit1 next`
- `npm dist-tag add thepackage@laststableversion.1.1 latest`
Which both show up like that in the "tags" section on the package info web page.
However, the recommended install command there, lists `npm i thepackage@futureversion.0.0-dev-commit2`. So, somewhere, setting the latest stable release did not fully go through. What would you recommend as the solution?

**Comment by ljharb** [comment]
@Dionysusnu it should work fine, but it might take a few minutes for the change to propagate out, especially if you're using a proxy or mirror of the npm registry (or an internal registry).

**Comment by Dionysusnu** [comment]
Forgot to report back, it seems to have worked in the end, the caches just took very long to update.

I had trouble finding this procedure, or even the CLI command at all. Is there any chance the discoverability could be improved?
