### ISSUE TITLE
Dark theme and better stats on npmjs.com

### ISSUE THREAD

**Issue by archnim** [npm/rfcs#577]
Hello world.

I would like to suggest that dark theme support be added on npmjs.com. It would be so relaxing for many sensible eyes !  For some people, screens light represent a great suffering.

I also think that for each package, there should be more statistics available, at least for the author.
- Downloads history in author's dashboard  (no need for external services like npm-stats)
- Downloads count updated more often (It currently seems to be updated every 24hrs)
I think stats should be added in the official website because, external sites maintained by one or two devs, can be abandoned at any time by their authors.

But the most important I think, is to provide an eye-caring theme. Thanks.

**Comment by ljharb** [comment]
See:
 - https://github.com/npm/feedback/discussions/420
 - https://github.com/npm/feedback/discussions/231
 - https://github.com/npm/feedback/discussions/656

**Comment by darcyclarke** [comment]
@archnim appreciate the feature request - that said, these types of website-releated ideas are best left on the [`npm/feedback` Discussion Board](https://github.com/npm/feedback/) (as @ljharb referenced). Going to close this for now as there's a few duplicates there that you can add to. Feel free to open another other issues for CLI-specific features/requests you may have here though.

**Comment by archnim** [comment]
Ok. Thank you 🙂
