### ISSUE TITLE
[RRFC] configs in in package.json

### ISSUE THREAD

**Issue by isaacs** [npm/rfcs#59]
Suggested in https://github.com/npm/rfcs/pull/36 

Request for an RFC to put a section in `package.json` which would function as a `project` level config, but also apply to scripts run in the course of installing the packages containing this config section.

Bikeshed on the name of the config section.  Established patterns from other cli tools (tap, jest, nyc, babel, typescript, etc.) would suggest that we call it `npm`.

```json
{
  "npm": {
    "script-shell": "/bin/bash"
  }
}
```

Argument against using `"npm"` as the key would be that it is a little weird to say "this bit of package.json is for npm", when really the _entire_ file is for npm.

Another tricky bit needing exploration is the impact of having these configuration values effectively set when running scripts in the course of installation and other lifecycle scenarios.  Replacing `./.npmrc` in the root project is relatively trivial by comparison.

**Comment by mkay581** [comment]
Yeah having the `npm` field would be rather odd in this case for the reason you've already stated, so vote no for that. But everything else seems reasonable but I'm not too familiar with every implication unfortunately.

**Comment by darcyclarke** [comment]
@isaacs was considering proposing support for a `.npmrc.json` file (similar to babel/eslint). This could allow for more verbose/structured config over the plaintext `.npmrc` files today. I'd imagine this would eventually become user's default/preferred method to setting config for `npm` specifically (beyond any existing/future `package.json` capabilities)
