### ISSUE TITLE
[RRFC] An option to stop after the first fail when running a script in workspaces

### ISSUE THREAD

**Issue by rpominov** [npm/rfcs#602]
## Motivation ("The Why")

I use `npm run build-and-test --workspaces` in a CI. If the script fails in one of the workspaces, it can be difficult to find the error in the CI log as it's followed by the output of the successful runs in the other workspaces.

#### Current Behaviour

There's no way that I know of to tell the cli to stop execution after the first fail.

#### Desired Behaviour

There's an option like --fail-fast.

### References

* n/a

**Comment by Twipped** [comment]
I literally JUST ran afoul of this exact problem. Test failures at package levels aren't halting CI workflows because `--workspaces` doesn't relay the error code.

**Comment by rpominov** [comment]
In my experience, it does relay the error code, just doesn't exit immediately. I believe the relevant code is here: https://github.com/npm/cli/blob/f2340f816f5a137038945229bf8a0d30160e76e8/lib/commands/run-script.js#L218-L222

If it exits with `0` code for you, updating npm may help.

**Comment by thescientist13** [comment]
I think this may be related to https://github.com/npm/rfcs/issues/575 , which has has some good conversations around this kind of behavior during the weekly meetings and so I think there is good traction on that issue.  (I noticed it has been tagged for release 8.x 👀 )

**Comment by rpominov** [comment]
Ah, great. I couldn't find an existing issue. This is a duplicate then.

**Comment by zymotik** [comment]
An npm cli `--fail-fast` flag has been waiting for a code review for over a year already, can someone help speed it along? https://github.com/npm/cli/pull/8323
