### ISSUE TITLE
public facing calendar is missing

### ISSUE THREAD

**Issue by jameskeyante** [npm/rfcs#664]
Sorry, maybe I missed something, I know there's the RFC meetings, but can't find the calendar for them - when is this going to be discussed? Is it better to wait for the meeting or post the questions now?

_Originally posted by @dominykas in https://github.com/npm/rfcs/issues/92#issuecomment-578555614_

**Comment by nlf** [comment]
Apologies for the confusion here, our calendar got lost after some team shuffling. We're working on getting a new one created that will be more permanent and will share it as soon as it's available. I'll keep this issue open until that work is done.

**Comment by ljharb** [comment]
@nlf note that this issue was spam-created off a comment in another issue

**Comment by nlf** [comment]
> @nlf note that this issue was spam-created off a comment in another issue

I noticed that but it is a valid issue since our calendar did, in fact, go missing
