### ISSUE TITLE
[RRFC] npm ls support flag to filter product dependencies only

### ISSUE THREAD

**Issue by HomyeeKing** [npm/rfcs#718]
### Example

```bash
npm ls lodash -P / --production # only list the dependencies used on runtime
```

#### Current Behaviour

list all kinds of dependencies 
#### Desired Behaviour

To keep project tiny, sometimes I want to check if some _runtime_ dependency has already imported by others, so I can improt it  no worries
### References

* n/a

**Comment by ljharb** [comment]
have you tried it? npm ls has always supported --production afaik

**Comment by HomyeeKing** [comment]
sorry, I have a typo
