### ISSUE TITLE
[QUESTION] <peerDependencies tips should be error>

### ISSUE THREAD

**Issue by cleverboy32** [npm/rfcs#74]
# What / Why

when i my package need an other package, i use peerDependencies to statement this point.  to hope others to install that package and install right version. but the result is, they install wrong version just a  warnging . its so Ignored。 i think the tips should be obviously error. beacuase if the packages need right peerDependencies. or i can defined the tips level  to remind people to note that 

![image](https://user-images.githubusercontent.com/17595456/70506053-6bf32d80-1b64-11ea-9c2d-e95e39bf3bbf.png)

really to ignore...

**Comment by isaacs** [comment]
npm v7 [will install peer deps by default](https://github.com/npm/rfcs/pull/43) (possibly as an opt-in or subsequent command, pending feedback from beta period), and will fail the installation if the peer dep graph cannot be resolved properly.

Doing anything different with peer deps would be a breaking change, and the current plan is to address this fully, so I think we can close this.
