### ISSUE TITLE
Feature: Tuya Web Plugin 

### ISSUE THREAD

**Issue by agentmikeyd** [npm/rfcs#84]
**What:**
Tuya Web Plugin 

**Current Behavior:**
Only dims and on and off for e12 bulbs. ### **Expected Behavior**:
Should be able to properly control color changes
Belfos did a great job already, and  this would make it perfect. Thanks

**Comment by mikemimik** [comment]
This seems unrelated to this project and organisation. This issue might be better suited for [r/homebridge](https://www.reddit.com/r/homebridge) community where you've [already posted](https://www.reddit.com/r/homebridge/comments/ej2tji/tuya_web_plugin_question/).
